### PR TITLE
Make download buttons reusable

### PR DESCRIPTION
**Pull request by ken-matsui**
This PR resolves the disadvantages of using an image as a button:
1. unnecessary data usage than not using images
2. character moire due to not supporting every display resolution, exceptionally high resolution
3. not reusable because we have to make a new image if we want to add more buttons

|  Current version  |  This PR  |
| ---- | ---- |
|  zellij dev_  |  localhost_1313_  |

The only differences I could not replicate are:
* font
* padding within the border

Therefore, please let me know what value you used if you would worry about the differences.

I removed redundant spaces in `themes/hello-friend-ng/assets/scss/_main.scss` and committed changes in the `resources` directory, but please let me know if you would like me to ignore their changes.

### CODE REVIEW

**Comment by ken-matsui** [comment]
Hi @a-kenji,

Since it seems the gh-pages branch is automatically deployed, I do not think we should include the `resources/_gen` directory.
Is there any reason to include the directory?

**Comment by a-kenji** [comment]
@ken-matsui,

The site is not updated, if you don't locally build with `hugo` and commit the changes. So I think it is necessary. But I am not too sure about that.

Maybe @TheLostLambda could chip in here.

**Comment by ken-matsui** [comment]
Hi @a-kenji,

Thank you for your insight. By seeing the [`gh-pages`](https://github.com/zellij-org/zellij-org.github.io/tree/gh-pages), it was updated by each commit on the `main` branch. Also, [GitHub Action](https://github.com/zellij-org/zellij-org.github.io/actions) shows deployments work well.

Thus, if the site is not updated, the source setting of GitHub Pages is possibly not set up correctly.
You can select the `gh-pages` branch as the deployment source in https://github.com/zellij-org/zellij-org.github.io/settings/pages.

**Comment by a-kenji** [comment]
Lets try it out! We can always revert it a little later.

**Comment by a-kenji** [comment]
Awesome, it does seem to work! Thanks so much.

**Comment by ken-matsui** [comment]
@a-kenji
Glad to hear that! You're welcome :)
I removed the conflicting files.

**Comment by ken-matsui** [comment]
@a-kenji (cc: @TheLostLambda)
Oh, I forgot about the https://github.com/zellij-org/zellij-org.github.io/issues/6 issue. I would say it now can be safely closed.

**Comment by a-kenji** [comment]
Thank you!

**Pull request merged**
