### PR TITLE
add room to plugin examples

### PR DESCRIPTION
**Pull request by rvcas**
this adds https://github.com/rvcas/room to the plugin examples

### CODE REVIEW

**Comment by imsnif** [comment]
Hey, thanks for putting this together! This repository is a bit weird and we also keep the compiled static files of the docs website. Could you build them (by running the `watch-serve` script at the root of this repo) and push again?

Thanks again, love the plugin!

**Comment by rvcas** [comment]
@imsnif no problem

**Comment by rvcas** [comment]
ok I ran `watch-serve` and only committed the relevant file. There were a bunch more changes that happened automatically like including `type` in all the script tags, perhaps maybe came from some updates to mdbook.

**Comment by imsnif** [comment]
Than you!

**Pull request merged**
