### PR TITLE
docs: add Alacritty to FAQ '.. use the Alt key?'

### PR DESCRIPTION
**Pull request by merikan**
Hi @imsnif 

I have updated the FAQ section `Macos users and Alt key` with a link for Alacritty. 
Since the option in Alacritty isn't released yet, I linked to my comment in [#2051](https://github.com/zellij-org/zellij/issues/2051).

### CODE REVIEW

**Comment by imsnif** [comment]
Hey @merikan - thanks for this!

The problem is that you only updated the generated source. You need to update the `md` file here: https://github.com/zellij-org/zellij-org.github.io/blob/main/docs/src/faq.md
Then run the included `watch-serve` script to build the project (and then look at the local website on localhost:1313 to make sure it was updated) and then commit everything.

**Comment by merikan** [comment]
Hi @imsnif 
Sorry, I didn't see the markdown file 😀 Fixed it.

**Comment by merikan** [comment]
Hi @imsnif 

I also updated the `compatibility` page so you can probably close #256 with a reference

**Comment by imsnif** [comment]
Thank you!!

**Pull request merged**
