### PR TITLE
Fix Mac OS default config file path

### PR DESCRIPTION
**Pull request by joshrotenberg**
Having just installed Zellij via cargo, I noticed that the documentation's path to the Mac OS file differs from what is actually created by the application. I have /Users/joshrotenberg/Library/Application\ Support/org.Zellij-Contributors.Zellij; org instead of com, and the trailing Zellij is capitalized.

This is on Big Sur 11.2.3

### CODE REVIEW

**Comment by imsnif** [comment]
Thanks for this!
One request: this site was created kind of quickly so some things are a little hacky. You need to run the site's watch script (`watch-serve.sh`) and then commit everything to this repository, otherwise the docs won't be built and deployed. Could you do that and then I'll happily merge this?

**Comment by joshrotenberg** [comment]
> One request: this site was created kind of quickly so some things are a little hacky. You need to run the site's watch script (`watch-serve.sh`) and then commit everything to this repository, otherwise the docs won't be built and deployed. Could you do that and then I'll happily merge this?

Yup, I'll do that now.

**Comment by joshrotenberg** [comment]
It doesn't look like the changes got processed just from running the script, but calling `mdbook build docs/ -d ../static/documentation` does rebuild everything. I committed the result of that, let me know if that's not right.

**Comment by joshrotenberg** [comment]
Haha wow, that's a lot of changes, hope that's ok!

**Comment by imsnif** [comment]
I'm going to ask @TheLostLambda for help on this one, to make sure we're not doing anything unbecoming. :)

**Comment by joshrotenberg** [comment]
I think the amount of changes was the result of my old mdbook version (my bad). I can redo the PR if that's preferred.

**Comment by a-kenji** [comment]
>I think the amount of changes was the result of my old mdbook version (my bad). I can redo the PR if that's preferred.

@joshrotenberg,
I think that would be the easiest way to go.

**Pull request closed without merging**
